### Pattern Mining

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("train_cleaned.csv")
df = df.replace({"explicit": {False:0, True:1}})

In [3]:
supp = pd.read_csv("supportConf.csv", index_col=0)
supp

        50   60   70  80  90
index
10     830  286  126  28   4
15     102   36   19   3   0
20      12    4    2   0   0
25       0    0    0   0   0
30       0    0    0   0   0

In [4]:
ruleshighpop = pd.read_csv("rules_high_pop.csv")
ruleshighpop

,consequent,antecedent,abs_support,%_support,confidence,lift
0,"HIGH_POP (24.0, 94.0]","('HIGH_ACOU (0.415, 0.996]', 'LOW_INST (-0.001...",1355,9.033333,0.732037,1.467204
1,"HIGH_POP (24.0, 94.0]","('MID_LOUD (-9.214, -5.791]', 'LOW_INST (-0.00...",1328,8.853333,0.715517,1.434094
2,"HIGH_POP (24.0, 94.0]","('HIGH_TEMP (134.984, 220.525]', 'LOW_INST (-0...",1303,8.686667,0.725097,1.453295
3,"HIGH_POP (24.0, 94.0]","('LOW_INST (-0.001, 1.27e-05]', 'LOW_ENER (-0....",1125,7.500000,0.742574,1.488324
4,"HIGH_POP (24.0, 94.0]","('LOW_INST (-0.001, 1.27e-05]', 'LOW_SPEE (-0....",1505,10.033333,0.775374,1.554062

In [5]:
ruleslowpop = pd.read_csv("rules_low_pop.csv")
ruleslowpop

,consequent,antecedent,abs_support,%_support,confidence,lift
0,"LOW_POP (-0.001, 24.0]","('HIGH_ENER (0.834, 1.0]', 'HIGH_INST (0.377, ...",1139,7.593333,0.723175,1.443270
1,"LOW_POP (-0.001, 24.0]","('HIGH_ENER (0.834, 1.0]', 'HIGH_DURA (265257....",1297,8.646667,0.701081,1.399177
2,"LOW_POP (-0.001, 24.0]","('HIGH_ENER (0.834, 1.0]', 'LOW_VALE (-0.001, ...",1059,7.060000,0.701325,1.399663
3,"LOW_POP (-0.001, 24.0]","('HIGH_INST (0.377, 1.0]', 'HIGH_DURA (265257....",1596,10.640000,0.746143,1.489109
4,"LOW_POP (-0.001, 24.0]","('HIGH_INST (0.377, 1.0]', 'LOW_ACOU (-0.001, ...",1495,9.966667,0.721525,1.439978

In [6]:
df_freq_it = pd.read_csv("df_freq_it.csv")
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)  # Show all columns
df_freq_it

,frequent_itemset,support
0,"HIGH_ACOU (0.415, 0.996], LOW_TEMP (-0.001, 109.646], LOW_LOUD (-49.532, -9.214], LOW_ENER (-0.001, 0.562]",9.373333
1,"HIGH_ACOU (0.415, 0.996], LOW_DURA (8585.999, 196231.667], LOW_LOUD (-49.532, -9.214], LOW_ENER (-0.001, 0.562]",9.193333
2,"HIGH_ACOU (0.415, 0.996], HIGH_INST (0.377, 1.0], LOW_LOUD (-49.532, -9.214], LOW_ENER (-0.001, 0.562]",9.400000
3,"HIGH_ACOU (0.415, 0.996], LOW_LOUD (-49.532, -9.214], LOW_DANC (-0.001, 0.496], LOW_ENER (-0.001, 0.562]",9.800000
4,"HIGH_ACOU (0.415, 0.996], LOW_LOUD (-49.532, -9.214], LOW_VALE (-0.001, 0.269], LOW_ENER (-0.001, 0.562]",9.966667
5,"LOW_LOUD (-49.532, -9.214], LOW_DANC (-0.001, 0.496], LOW_VALE (-0.001, 0.269], LOW_ENER (-0.001, 0.562]",9.420000

In [7]:
rules_freq= pd.read_csv("rules_df.csv")
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)  # Show all columns

sorted_rules_freq = rules_freq.sort_values(by='lift', ascending=False)

sorted_rules_freq

,consequent,antecedent,abs_support,%_support,confidence,lift
1,"LOW_LOUD (-49.532, -9.214]","HIGH_ACOU (0.415, 0.996], HIGH_INST (0.377, 1.0], LOW_ENER (-0.001, 0.562]",1410,9.400000,0.922171,2.766514
0,"LOW_ENER (-0.001, 0.562]","HIGH_ACOU (0.415, 0.996], LOW_TEMP (-0.001, 109.646], LOW_LOUD (-49.532, -9.214]",1406,9.373333,0.913580,2.735816
3,"LOW_ENER (-0.001, 0.562]","HIGH_ACOU (0.415, 0.996], LOW_LOUD (-49.532, -9.214], LOW_VALE (-0.001, 0.269]",1495,9.966667,0.911030,2.728179
2,"LOW_ENER (-0.001, 0.562]","HIGH_ACOU (0.415, 0.996], LOW_LOUD (-49.532, -9.214], LOW_DANC (-0.001, 0.496]",1470,9.800000,0.900735,2.697351

### POP CONF

In [8]:
RULES_high_pop_conf=pd.read_csv("RULES_high_pop_conf.csv")
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)  # Show all columns
RULES_high_pop_conf

,consequent,antecedent,abs_support,%_support,confidence,lift
0,"HIGH_POP_CONF (0.656, 1.0]","('HIGH_ENER (0.829, 1.0]', 'HIGH_LIVE (0.204, 0.994]', 'HIGH_LOUD (-5.856, 0.643]')",99,4.465494,0.407407,1.222222
1,"HIGH_POP_CONF (0.656, 1.0]","('HIGH_ENER (0.829, 1.0]', 'HIGH_LOUD (-5.856, 0.643]', 'HIGH_SPEE (0.0687, 0.901]')",114,5.142084,0.425373,1.276119
2,"HIGH_POP_CONF (0.656, 1.0]","('HIGH_ENER (0.829, 1.0]', 'MID_DANC (0.504, 0.658]')",102,4.600812,0.408000,1.224000
3,"HIGH_POP_CONF (0.656, 1.0]","('HIGH_LIVE (0.204, 0.994]', 'HIGH_SPEE (0.0687, 0.901]')",124,5.593144,0.423208,1.269625
4,"HIGH_POP_CONF (0.656, 1.0]","('MID_INST (1.27e-05, 0.341]', 'HIGH_DURA (266593.667, 1149106.0]')",101,4.555706,0.413934,1.241803
5,"HIGH_POP_CONF (0.656, 1.0]","('HIGH_LOUD (-5.856, 0.643]', 'HIGH_SPEE (0.0687, 0.901]')",140,6.314840,0.408163,1.224490
6,"HIGH_POP_CONF (0.656, 1.0]","('MID_TEMP (109.759, 134.948]', 'LOW_INST (-0.001, 1.27e-05]')",96,4.330176,0.406780,1.220339

In [9]:
RULES_mid_pop_conf=pd.read_csv("RULES_mid_pop_conf.csv")
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)  # Show all columns
RULES_mid_pop_conf

,consequent,antecedent,abs_support,%_support,confidence,lift
0,"MID_POP_CONF (0.318, 0.656]","('HIGH_VALE (0.575, 0.995]', 'HIGH_TEMP (134.948, 220.525]')",104,4.691024,0.403101,1.209302

In [10]:
RULES_low_pop_conf=pd.read_csv("RULES_low_pop_conf.csv")
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)  # Show all columns
RULES_low_pop_conf

,consequent,antecedent,abs_support,%_support,confidence,lift
0,"LOW_POP_CONF (-0.001, 0.318]","('HIGH_LIVE (0.204, 0.994]', 'LOW_TEMP (-0.001, 109.759]')",95,4.285070,0.400844,1.202532
1,"LOW_POP_CONF (-0.001, 0.318]","('LOW_TEMP (-0.001, 109.759]', 'LOW_INST (-0.001, 1.27e-05]')",98,4.420388,0.404959,1.214876

In [11]:
df.head()

,name,duration_ms,explicit,popularity,artists,album_name,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre
0,Long Road,241760,0,46,Funki Porcini,Hed Phone Sex,0.690,0.513,5,-12.529,0.0975,0.302000,0.53600,0.281,0.6350,142.221,4.0,j-dance
1,"Daniâl My Son, Where Did You Vanish?",444000,0,0,Siavash Amini,A Trail of Laughters,0.069,0.196,1,-24.801,0.0805,0.283000,0.93400,0.360,0.0336,75.596,4.0,iranian
2,Ondskapens Galakse,333506,0,3,Kvelertak,Nattesferd,0.363,0.854,2,-7.445,0.0397,0.000089,0.80000,0.262,0.4890,116.628,4.0,black-metal
3,Can't Look Away,269800,0,23,The Wood Brothers,One Drop of Truth,0.523,0.585,5,-5.607,0.0765,0.066400,0.00127,0.117,0.3850,140.880,4.0,bluegrass
4,Thunderground,307651,0,25,The Darkraver;DJ Vince,Happy Hardcore Top 100,0.643,0.687,7,-11.340,0.0539,0.000576,0.09690,0.299,0.6370,143.956,4.0,happy

## Feature preprocessing (light)

In [12]:
# remove useless variables
column2drop = ["name", "artists", "album_name"]
df.drop(column2drop, axis=1, inplace=True)

In [13]:
df.head()

,duration_ms,explicit,popularity,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre
0,241760,0,46,0.690,0.513,5,-12.529,0.0975,0.302000,0.53600,0.281,0.6350,142.221,4.0,j-dance
1,444000,0,0,0.069,0.196,1,-24.801,0.0805,0.283000,0.93400,0.360,0.0336,75.596,4.0,iranian
2,333506,0,3,0.363,0.854,2,-7.445,0.0397,0.000089,0.80000,0.262,0.4890,116.628,4.0,black-metal
3,269800,0,23,0.523,0.585,5,-5.607,0.0765,0.066400,0.00127,0.117,0.3850,140.880,4.0,bluegrass
4,307651,0,25,0.643,0.687,7,-11.340,0.0539,0.000576,0.09690,0.299,0.6370,143.956,4.0,happy

## Pattern mining preprocessing

In [14]:
df["durationBin"] = pd.qcut(df["duration_ms"], 10, duplicates='drop')
df["popularityBin"] = pd.qcut(df["popularity"], 10, duplicates='drop')
df["danceabilityBin"] = pd.qcut(df["danceability"], 10, duplicates='drop')
df["energyBin"] = pd.qcut(df["energy"], 10, duplicates='drop')
df["loudnessBin"] = pd.qcut(df["loudness"], 10, duplicates='drop')
df["speechinessBin"] = pd.qcut(df["speechiness"], 10, duplicates='drop')
df["acousticnessBin"] = pd.qcut(df["acousticness"], 10, duplicates='drop')
df["instrumentalnessBin"] = pd.qcut(df["instrumentalness"], 10, duplicates='drop')
df["livenesssBin"] = pd.qcut(df["liveness"], 10, duplicates='drop')
df["valenceBin"] = pd.qcut(df["valence"], 10, duplicates='drop')
df["tempoBin"] = pd.qcut(df["tempo"], 10, duplicates='drop')

df.drop(['duration_ms', 'popularity', 'danceability', 'energy', 'loudness', 'speechiness', 'acousticness','instrumentalness', 'liveness', 'valence', 'tempo'], axis=1, inplace=True)

In [15]:
df.head()

,explicit,key,time_signature,genre,durationBin,popularityBin,danceabilityBin,energyBin,loudnessBin,speechinessBin,acousticnessBin,instrumentalnessBin,livenesssBin,valenceBin,tempoBin
0,0,5,4.0,j-dance,"(227826.0, 248911.6]","(38.0, 46.0]","(0.672, 0.719]","(0.418, 0.527]","(-16.164, -11.899]","(0.0761, 0.105]","(0.3, 0.477]","(0.089, 0.575]","(0.235, 0.321]","(0.612, 0.715]","(137.97, 149.82]"
1,0,1,4.0,iranian,"(373777.2, 4120258.0]","(-0.001, 1.0]","(-0.001, 0.251]","(-0.001, 0.259]","(-49.532, -16.164]","(0.0761, 0.105]","(0.155, 0.3]","(0.902, 1.0]","(0.321, 0.445]","(-0.001, 0.0642]","(-0.001, 82.135]"
2,0,2,4.0,black-metal,"(307617.6, 373777.2]","(1.0, 10.0]","(0.251, 0.399]","(0.788, 0.855]","(-8.37, -7.303]","(0.0396, 0.0446]","(-0.001, 0.000401]","(0.575, 0.826]","(0.235, 0.321]","(0.416, 0.511]","(104.984, 117.048]"
3,0,5,4.0,bluegrass,"(248911.6, 273471.2]","(21.0, 24.0]","(0.477, 0.532]","(0.527, 0.625]","(-6.404, -5.511]","(0.0761, 0.105]","(0.0204, 0.0686]","(0.00011, 0.00313]","(0.113, 0.131]","(0.328, 0.416]","(137.97, 149.82]"
4,0,7,4.0,happy,"(307617.6, 373777.2]","(24.0, 30.0]","(0.625, 0.672]","(0.625, 0.709]","(-11.899, -9.729]","(0.051, 0.0601]","(0.000401, 0.00394]","(0.089, 0.575]","(0.235, 0.321]","(0.612, 0.715]","(137.97, 149.82]"

In [16]:
df["AgeBin"] = df["AgeBin"].astype(str) + "_Age"
df["FareBin"] = df["FareBin"].astype(str) + "_Fare"
df["Embarked"] = df["Embarked"] + "_Port"

KeyError: 'AgeBin'

In [ ]:
df.head()

In [ ]:
surv_dict = {0: "Not Survived", 1: "Survived"}
df["Survived"] = df["Survived"].map(surv_dict)

pclass_dict = {1: "1st_class", 2: "2nd_class", 3: "3rd_class"}
df["Pclass"] = df["Pclass"].map(pclass_dict)

In [ ]:
df.head()

In [ ]:
X = df.values.tolist()

In [ ]:
X[0]

# Pattern Mining

## Apriori

In [ ]:
from fim import apriori

In [ ]:
help(apriori)

In [ ]:
# frequent itemset >= min_supp
# closed: an itemset is closed if none of its immediate supersets has the same support as the itemset
# maximal: an itemset is maximal frequent if none of its immediate supersets is frequent

### Frequent Itemset

In [ ]:
# supp = 2  # 2%
supp = 20  # 20%
zmin = 2  # minimum number of items per item set

itemsets = apriori(X, target="s", supp=supp, zmin=zmin, report="S")
pd.DataFrame(itemsets, columns=["frequent_itemset", "support"])

### Closed Itemsets

In [ ]:
# supp = 2  # 2%
supp = 20  # 20%
zmin = 2  # minimum number of items per item set

itemsets = apriori(X, target="c", supp=supp, zmin=zmin, report="S")
pd.DataFrame(itemsets, columns=["closed_itemset", "support"])

### Maximal Itemsets

In [ ]:
itemsets = apriori(X, target="m", supp=supp, zmin=zmin, report="S")
pd.DataFrame(itemsets, columns=["maximal_itemset", "support"])

### Support plots

#### Support vs number of itemsets

In [ ]:
len_max_it = []
len_cl_it = []
max_supp = 25
for i in range(2, max_supp):
    max_itemsets = apriori(X, target="m", supp=i, zmin=zmin)
    cl_itemsets = apriori(X, target="c", supp=i, zmin=zmin)
    len_max_it.append(len(max_itemsets))
    len_cl_it.append(len(cl_itemsets))

plt.plot(np.arange(2, max_supp), len_max_it, label="maximal")
plt.plot(np.arange(2, max_supp), len_cl_it, label="closed")
plt.legend()
plt.xlabel("%support")
plt.ylabel("itemsets")

plt.show()

#### Support vs number of itemset for survived / not survived

In [ ]:
filter_1 = []
filter_2 = []
for i in range(2, max_supp):
    max_itemsets = apriori(X, target="m", supp=i, zmin=zmin)
    filter_1.append(len([item for item in max_itemsets if "Survived" in item[0]]))
    filter_2.append(len([item for item in max_itemsets if "Not Survived" in item[0]]))

plt.plot(np.arange(2, max_supp), filter_1, label="w/ Survived")
plt.plot(np.arange(2, max_supp), filter_2, label="w/ Not Survived")
plt.legend()
plt.xticks()
plt.xlabel("%support")
plt.ylabel("itemsets")

plt.show()

### Rules

In [ ]:
help(apriori)

if the target is association rules:
                a list of rules (i.e. tuples with two or more elements),
                each consisting of a head/consequent item, a tuple with
                a body/antecedent item set, and the values selected by
                the parameter 'report', which may be combined into a
                tuple or a list if report[0] is '(' or '[', respectively.

In [ ]:
conf = 60
rules = apriori(X, target="r", supp=supp, zmin=zmin, conf=conf, report="aScl")
rules_df = pd.DataFrame(
    rules,
    columns=[
        "consequent",
        "antecedent",
        "abs_support",
        "%_support",
        "confidence",
        "lift",
    ],
)
rules_df.sort_values(by="lift", axis=0, ascending=False)

### Classification

In [ ]:
rules_df[rules_df["consequent"] == "Survived"]

In [ ]:
print("to_predict:", [r for r in rules if r[0] == "Survived"][0][0])
print("how?", [r for r in rules if r[0] == "Survived"][0][1])

In [ ]:
# left for exercise

# using the same test set for classification (w/ random_state):
# predict the target variable with the most interesting rule:
# .... e.g., the most frequent;
# .... e.g., the one w/ max lift
# build a list of prediction, e.g. ['Survived', 'Not Survived', 'Survived']
# evaluate this prediction with precision/recall/confusion matrix etc.

In [ ]:
len_r = []
min_sup = 1
max_sup = 20
min_conf = 50
max_conf = 90
for i in range(min_sup, max_sup):  # support
    len_r_wrt_i = []
    for j in range(min_conf, max_conf):  # confidence
        rules = apriori(X, target="r", supp=i, zmin=zmin, conf=j, report="aScl")
        len_r_wrt_i.append(len(rules))  # study your characteristics/properties here

    len_r.append(len_r_wrt_i)
len_r = np.array(len_r)

In [ ]:
sns.heatmap(len_r, cmap="Blues", fmt='g')
plt.yticks(np.arange(0, max_sup-min_sup +1, 5), np.arange(min_sup, max_sup+1,5 ))
plt.xticks(np.arange(0, max_conf-min_conf+1, 5), np.arange(min_conf, max_conf+1, 5))
plt.xlabel("%confidence")
plt.ylabel("%support")
plt.show()

## FP-Growth

In [ ]:
from fim import fpgrowth

In [ ]:
help(fpgrowth)

In [ ]:
supp = 2  # 2%
supp = 20  # 20%
zmin = 2  # minimum number of items per item set

itemsets = fpgrowth(X, target="s", supp=supp, zmin=zmin, report="S")
pd.DataFrame(itemsets, columns=["frequent_itemset", "support"])

In [ ]:
conf = 70
rules = fpgrowth(X, target="r", supp=supp, zmin=zmin, conf=conf, report="aScl")
pd.DataFrame(
    rules,
    columns=[
        "consequent",
        "antecedent",
        "abs_support",
        "%_support",
        "confidence",
        "lift",
    ],
)